USE sakila;
SHOW tables;

-- CHALLENGE - Write SQL queries to perform the following tasks using the Sakila database:
-- List the number of films per category.
SELECT 
    category.name AS category,
    COUNT(film_category.film_id) AS total_films
FROM category
JOIN film_category ON category.category_id = film_category.category_id
GROUP BY category.name
ORDER BY total_films DESC;

-- Retrieve the store ID, city, and country for each store.
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT 
    st.store_id,
    SUM(p.amount) AS total_revenue
FROM payment p
JOIN staff s ON p.staff_id = s.staff_id
JOIN store st ON s.store_id = st.store_id
GROUP BY st.store_id
ORDER BY total_revenue DESC;

-- Determine the average running time of films for each category.
SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_duration
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY avg_duration DESC;

-- Bonus:
-- Identify the film categories with the longest average running time.
SELECT 
    c.name AS category,
    ROUND(AVG(f.length), 2) AS avg_duration
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY avg_duration DESC;

-- Display the top 10 most frequently rented movies in descending order.
SELECT 
    f.title,
    COUNT(*) AS total_rentals
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
GROUP BY f.title
ORDER BY total_rentals DESC
LIMIT 10;

-- Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT 
    f.title,
    i.store_id
FROM film f
JOIN inventory i ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
  AND i.store_id = 1;

-- Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement
-- combined with IFNULL.
SELECT
    f.title,
    CASE
        WHEN COUNT(i.inventory_id) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability
FROM film f
LEFT JOIN inventory i ON f.film_id = i.film_id
GROUP BY f.title
ORDER BY availability DESC, f.title ASC;
